# Real failed startup postmortems from around the world
# Schema: title, desc, model, effort, speed, category, persona, tags, region, year_founded, year_shutdown, funding, failure_reason

POSTMORTEMS = [
    # ===== INDIA =====
    {
        "title": "Byju's",
        "desc": "India's most valuable edtech startup at $22B. Offered online learning apps and test prep. Collapsed after aggressive M&A spree, delayed audits, governance failures, and post-pandemic demand normalization. Founder sentenced to jail for contempt.",
        "model": "Freemium",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "EdTech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "Mobile App", "VC-Backable", "High Churn"],
        "region": "India",
        "year_founded": 2011,
        "year_shutdown": 2024,
        "funding": "$5.5B",
        "failure_reason": "Unsustainable growth & governance"
    },
    {
        "title": "Zilingo",
        "desc": "Singapore-HQ fashion tech platform connecting Southeast Asian manufacturers to global brands. Valued at $1B+. Collapsed after CEO was suspended for financial irregularities, Kroll investigation found revenue discrepancies, board-level conflicts escalated.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Ecommerce",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "Marketplace", "VC-Backable", "Cold Start Risk"],
        "region": "India",
        "year_founded": 2015,
        "year_shutdown": 2023,
        "funding": "$300M",
        "failure_reason": "Governance & financial irregularities"
    },
    {
        "title": "BharatPe",
        "desc": "Indian fintech for merchant payments and UPI QR codes. Valued at $2.8B at peak. Near-collapse after co-founder Ashneer Grover's removal over alleged financial misconduct, governance lapses, and inflated metrics. Survived in reduced form after restructuring.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Fintech",
        "persona": "The B2B SaaS Veteran",
        "tags": ["B2B", "VC-Backable", "Regulatory Risk", "Bootstrap-Friendly"],
        "region": "India",
        "year_founded": 2018,
        "year_shutdown": 2023,
        "funding": "$700M",
        "failure_reason": "Governance & co-founder conflict"
    },
    {
        "title": "GoMechanic",
        "desc": "Indian auto repair marketplace connecting car owners with service centers. Founders admitted inflating revenue 5-6x over multiple years. EY audit revealed accounting violations. Sequoia-backed implosion due to systematic financial fraud.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Medium Runway",
        "category": "Local Services",
        "persona": "The Realistic Side-Hustler",
        "tags": ["Marketplace", "B2C", "VC-Backable", "Cold Start Risk"],
        "region": "India",
        "year_founded": 2016,
        "year_shutdown": 2023,
        "funding": "$120M",
        "failure_reason": "Financial fraud"
    },
    {
        "title": "Good Glamm Group",
        "desc": "Indian D2C beauty and personal care conglomerate. Rolled up multiple brands via debt-fueled acquisitions. Valued at $1.2B. Collapsed due to high leverage, delayed profitability, working-capital stress, and inability to refinance.",
        "model": "Subscription",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Ecommerce",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "High Churn", "Marketplace"],
        "region": "India",
        "year_founded": 2016,
        "year_shutdown": 2025,
        "funding": "$270M",
        "failure_reason": "Debt-fuelled overexpansion"
    },
    {
        "title": "Hike",
        "desc": "Indian messaging app that once challenged WhatsApp. Raised heavily from Tiger Global and SoftBank. Failed due to loss of core relevance against WhatsApp, failed pivots into gaming/Web3, declining user engagement, and no PMF in new directions.",
        "model": "Freemium",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Media",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "Viral", "Mobile App"],
        "region": "India",
        "year_founded": 2012,
        "year_shutdown": 2025,
        "funding": "$250M",
        "failure_reason": "Lost relevance, failed pivots"
    },
    {
        "title": "Dunzo",
        "desc": "Indian hyperlocal delivery and task management platform. Google and Reliance-backed. Shut down due to unsustainable unit economics, high burn rate per order, inability to compete with Zepto/Blinkit on quick commerce, and funding pullback.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "India",
        "year_founded": 2014,
        "year_shutdown": 2025,
        "funding": "$380M",
        "failure_reason": "Unsustainable unit economics"
    },
    {
        "title": "BluSmart",
        "desc": "Indian electric vehicle ride-hailing fleet. Capital-intensive model with high fixed costs. Shut down when funding winter hit, unable to sustain EV fleet operations despite long-term promise. Governance risks compounded capital constraints.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Regulatory Risk"],
        "region": "India",
        "year_founded": 2019,
        "year_shutdown": 2025,
        "funding": "$200M",
        "failure_reason": "Capital intensity + funding winter"
    },
    {
        "title": "Builder.ai",
        "desc": "AI-powered no-code app building platform. Valued at $600M+. Shut down when AI hype outpaced product reality. Execution gaps, governance issues, and cash-flow problems despite significant funding from Qatar Investment Authority.",
        "model": "SaaS",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "DevTools",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "AI-Wrapper", "No-Code"],
        "region": "India",
        "year_founded": 2016,
        "year_shutdown": 2025,
        "funding": "$450M",
        "failure_reason": "AI hype vs product reality"
    },
    {
        "title": "Altigreen",
        "desc": "Indian electric vehicle manufacturer backed by Reliance. Shut down its Karnataka manufacturing unit after failing to raise new funds amid mounting losses and liabilities. EV market was real but capital intensity was fatal.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Regulatory Risk"],
        "region": "India",
        "year_founded": 2013,
        "year_shutdown": 2025,
        "funding": "$50M",
        "failure_reason": "Capital intensity + funding failure"
    },

    # ===== UNITED STATES =====
    {
        "title": "Convoy",
        "desc": "Digital freight brokerage connecting shippers with carriers. Raised $1B, valued at $4B. Founded by Amazon alumni. Failed because money-losing model couldn't become profitable, executives lacked trucking industry experience, and market turned post-pandemic.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "US",
        "year_founded": 2015,
        "year_shutdown": 2023,
        "funding": "$1B",
        "failure_reason": "Unprofitable model, industry inexperience"
    },
    {
        "title": "Olive AI",
        "desc": "Healthcare AI automation for insurance verification and prior authorization. Raised $850M, valued at $4B. Failed because AI pitch overstated capability (heavy manual intervention needed), overhired, lost focus through rapid expansion, and market turned.",
        "model": "SaaS",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Health",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "AI-Wrapper", "Enterprise"],
        "region": "US",
        "year_founded": 2012,
        "year_shutdown": 2023,
        "funding": "$850M",
        "failure_reason": "Overpromised AI, premature scaling"
    },
    {
        "title": "Quibi",
        "desc": "Mobile-first short-form video streaming platform with Hollywood talent. Raised $1.75B. Failed spectacularly due to no market need — launched during pandemic when people were home watching long-form, mobile-only was a constraint not a feature, and subscription for short clips made no sense.",
        "model": "Subscription",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Media",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "Mobile App", "Viral"],
        "region": "US",
        "year_founded": 2018,
        "year_shutdown": 2020,
        "funding": "$1.75B",
        "failure_reason": "No market need, wrong timing"
    },
    {
        "title": "WeWork",
        "desc": "Co-working space provider that raised $11.5B and reached $47B valuation. IPO implosion revealed fundamentally broken unit economics, founder governance failures, and inflated metrics. Adam Neumann ousted, company restructured through bankruptcy.",
        "model": "Subscription",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "PropTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Enterprise", "High Churn"],
        "region": "US",
        "year_founded": 2010,
        "year_shutdown": 2023,
        "funding": "$11.5B",
        "failure_reason": "Broken unit economics, governance failures"
    },
    {
        "title": "Theranos",
        "desc": "Blood testing startup promising revolutionary diagnostics from a finger prick. Raised $700M, valued at $9B. Completely fraudulent technology that never worked. CEO Elizabeth Holmes convicted of fraud and sentenced to prison.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Health",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "B2B", "VC-Backable", "Regulatory Risk"],
        "region": "US",
        "year_founded": 2003,
        "year_shutdown": 2018,
        "funding": "$700M",
        "failure_reason": "Fraud, technology never worked"
    },
    {
        "title": "FTX",
        "desc": "Cryptocurrency exchange founded by Sam Bankman-Fried. Raised $2B, valued at $32B. Collapsed overnight when revealed that customer funds were used to prop up Alameda Research hedge fund. $8B in customer funds missing. Founder convicted of fraud.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Quick Cash",
        "category": "Crypto",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "Regulatory Risk", "Marketplace"],
        "region": "US",
        "year_founded": 2017,
        "year_shutdown": 2022,
        "funding": "$2B",
        "failure_reason": "Massive fraud, customer fund misuse"
    },
    {
        "title": "MoviePass",
        "desc": "Subscription service for unlimited movie theater tickets. Raised $200M. Priced at $9.99/month for unlimited movies — fundamentally unsustainable unit economics. Heavy users cost far more than subscription revenue. Burned cash until collapse.",
        "model": "Subscription",
        "effort": "3-6 Months",
        "speed": "Quick Cash",
        "category": "Media",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "High Churn"],
        "region": "US",
        "year_founded": 2011,
        "year_shutdown": 2020,
        "funding": "$200M",
        "failure_reason": "Unsustainable unit economics"
    },
    {
        "title": "Pebble",
        "desc": "Pioneering smartwatch company that raised $20M+ on Kickstarter. Created the smartwatch category before Apple Watch. Failed when Apple entered the market, supply chain couldn't compete, and pricing pressure destroyed margins. Acquired by Fitbit for fire-sale price.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Medium Runway",
        "category": "Design",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Crowdfunded", "Hardware"],
        "region": "US",
        "year_founded": 2012,
        "year_shutdown": 2016,
        "funding": "$25M",
        "failure_reason": "Platform risk (Apple), hardware margins"
    },
    {
        "title": "Jawbone",
        "desc": "Wearable fitness tracker and Bluetooth speaker company. Raised $900M. Failed due to supply chain issues, manufacturing delays, legal battles with Fitbit, and inability to compete in rapidly commoditizing fitness tracker market.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Medium Runway",
        "category": "Design",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Hardware"],
        "region": "US",
        "year_founded": 1997,
        "year_shutdown": 2017,
        "funding": "$900M",
        "failure_reason": "Supply chain, competition, execution"
    },
    {
        "title": "Webvan",
        "desc": "Online grocery delivery service during dot-com era. Raised $400M+ and built massive infrastructure before validating demand. Spent $1B on warehouses and delivery infrastructure. Collapsed when revenue never materialized — 8 months after IPO.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "US",
        "year_founded": 1996,
        "year_shutdown": 2001,
        "funding": "$400M",
        "failure_reason": "Built infrastructure before demand validation"
    },

    # ===== EUROPE =====
    {
        "title": "Northvolt",
        "desc": "Swedish battery gigafactory startup, Europe's great green hope. Raised $14B+ including $5B green loan. Filed Chapter 11 after production delays, cost overruns, softening EV demand, and BMW pulling out. Proved capital intensity alone can kill even well-funded ventures.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Regulatory Risk", "Enterprise"],
        "region": "Europe",
        "year_founded": 2016,
        "year_shutdown": 2024,
        "funding": "$14B",
        "failure_reason": "Overambitious scaling, demand mismatch"
    },
    {
        "title": "Lilium",
        "desc": "German electric vertical takeoff and landing (eVTOL) flying taxi company. Raised $1B+, went public via SPAC. Filed for bankruptcy twice. eVTOL hype cycle ended, certification timelines unrealistic, capital needs massive, revenue non-existent.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "B2B", "VC-Backable", "Regulatory Risk"],
        "region": "Europe",
        "year_founded": 2015,
        "year_shutdown": 2025,
        "funding": "$1.5B",
        "failure_reason": "Unrealistic timelines, capital intensity"
    },
    {
        "title": "N26 (UK operations)",
        "desc": "German neobank that expanded to UK then withdrew. Raised $1.8B overall. UK operations failed due to regulatory issues with FCA, inability to compete with Monzo/Revolut, and strategic retreat to focus on core European markets.",
        "model": "Subscription",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Fintech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Regulatory Risk", "Mobile App"],
        "region": "Europe",
        "year_founded": 2013,
        "year_shutdown": 2024,
        "funding": "$1.8B",
        "failure_reason": "Regulatory challenges, market competition"
    },
    {
        "title": "Deliveroo (Australia)",
        "desc": "Food delivery platform that exited Australian market after $600M+ investment. Couldn't compete with Uber Eats and DoorDash. Failed due to high marketing costs, low unit economics, and inability to achieve market leadership in a commoditized space.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "Marketplace", "VC-Backable", "Cold Start Risk"],
        "region": "Europe",
        "year_founded": 2013,
        "year_shutdown": 2024,
        "funding": "$600M",
        "failure_reason": "Unit economics, competition"
    },

    # ===== SOUTHEAST ASIA =====
    {
        "title": "Honestbee",
        "desc": "Singapore-based online grocery delivery. Raised $350M, valued at $1B+. Collapsed due to massive cash burn, inability to achieve profitability in competitive SEA market, and operational issues including unpaid supplier bills. Employees laid off without severance.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "SEA",
        "year_founded": 2015,
        "year_shutdown": 2023,
        "funding": "$350M",
        "failure_reason": "Cash burn, unprofitable unit economics"
    },
    {
        "title": "Ula",
        "desc": "Indonesian B2B e-commerce platform for small retailers. Raised $140M from Sequoia and others. Collapsed despite addressing a real problem because unit economics didn't work for low-margin FMCG goods in a price-sensitive market with cash-based transactions.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Ecommerce",
        "persona": "The B2B SaaS Veteran",
        "tags": ["B2B", "VC-Backable", "Marketplace"],
        "region": "SEA",
        "year_founded": 2019,
        "year_shutdown": 2024,
        "funding": "$140M",
        "failure_reason": "Unit economics in low-margin B2B"
    },
    {
        "title": "Carousell (down round)",
        "desc": "Singapore classifieds marketplace. Valued at $1B+ at peak. Massive layoffs and flat/down rounds after advertising revenue collapsed and competition from Facebook Marketplace intensified. Survived in reduced form but destroyed investor returns.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Ecommerce",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Mobile App"],
        "region": "SEA",
        "year_founded": 2012,
        "year_shutdown": 2024,
        "funding": "$360M",
        "failure_reason": "Revenue collapse, Facebook competition"
    },

    # ===== LATIN AMERICA =====
    {
        "title": "Kavak (Mexico retraction)",
        "desc": "Mexican used car marketplace. Raised $1.6B, valued at $8.7B. Massive retraction after over-expansion into multiple countries. Laid off 50%+ staff, withdrew from multiple markets when funding dried up and used car financing costs rose with interest rates.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Ecommerce",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "LATAM",
        "year_founded": 2016,
        "year_shutdown": 2024,
        "funding": "$1.6B",
        "failure_reason": "Overexpansion, interest rate sensitivity"
    },
    {
        "title": "Rappi (valuation collapse)",
        "desc": "Colombian on-demand delivery startup. Raised $2B+, valued at $5.2B peak. Valuation collapsed 80%+ as growth slowed and profitability remained elusive. Heavy subsidies required to maintain market share against iFood and others.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Marketplace", "Cold Start Risk"],
        "region": "LATAM",
        "year_founded": 2015,
        "year_shutdown": 2024,
        "funding": "$2B",
        "failure_reason": "Unsustainable subsidies, no profitability"
    },

    # ===== AFRICA =====
    {
        "title": "Twiga Foods",
        "desc": "Kenyan B2B food supply platform connecting farmers to vendors. Raised $150M. Collapsed due to thin margins in African agri-procurement, difficulty collecting payments from informal vendors, and working capital constraints that made the model unsustainable at scale.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Logistics",
        "persona": "The Realistic Side-Hustler",
        "tags": ["B2B", "VC-Backable", "Marketplace"],
        "region": "Africa",
        "year_founded": 2014,
        "year_shutdown": 2024,
        "funding": "$150M",
        "failure_reason": "Thin margins, payment collection issues"
    },
    {
        "title": "Andela (pivot from core)",
        "desc": "African tech talent marketplace connecting developers to global companies. Raised $200M. Original model (train + place developers) failed because unit economics didn't work. Pivoted to remote hiring platform. Original model's failure showed cost of training arbitrage.",
        "model": "Marketplace",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CareerTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Marketplace"],
        "region": "Africa",
        "year_founded": 2014,
        "year_shutdown": 2023,
        "funding": "$200M",
        "failure_reason": "Unit economics of training arbitrage"
    },

    # ===== GLOBAL / CROSS-REGION =====
    {
        "title": "Terra/Luna",
        "desc": "Algorithmic stablecoin ecosystem on blockchain. Raised $200M+, at peak had $40B+ market cap. Algorithmic stablecoin design proved to be a reflexive ponzi — when Luna price dropped, the stablecoin de-pegged, triggering a death spiral that wiped out $40B in hours.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Quick Cash",
        "category": "Crypto",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "Regulatory Risk", "Viral"],
        "region": "Global",
        "year_founded": 2018,
        "year_shutdown": 2022,
        "funding": "$200M",
        "failure_reason": "Algorithmic stablecoin death spiral"
    },
    {
        "title": "Wirecard",
        "desc": "German payment processing giant, once valued at $28B. Raised $3B+. Collapsed when it was revealed that $2B in cash on its balance sheet didn't exist. Massive accounting fraud on a corporate scale. CEO arrested. One of Europe's biggest frauds since Madoff.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Fintech",
        "persona": "The B2B SaaS Veteran",
        "tags": ["B2B", "VC-Backable", "Enterprise", "Regulatory Risk"],
        "region": "Europe",
        "year_founded": 1999,
        "year_shutdown": 2020,
        "funding": "$3B",
        "failure_reason": "Massive accounting fraud"
    },
    {
        "title": "Plenty (vertical farming)",
        "desc": "US vertical farming startup. Raised $1B+, valued at $1.7B. Filed Chapter 11 in 2025. Vertical farming proved structurally uneconomic at scale — energy costs for LED lighting + climate control exceeded crop value for all but the highest-margin produce.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "B2B", "VC-Backable", "Hardware"],
        "region": "US",
        "year_founded": 2013,
        "year_shutdown": 2025,
        "funding": "$1B",
        "failure_reason": "Structural uneconomics of vertical farming"
    },
    {
        "title": "Motif FoodWorks",
        "desc": "US alternative protein company. Raised $344M from investors including Bill Gates. Shut down when alt-protein consumer adoption failed to materialize at expected scale. Built production capacity for demand that never came. Market infrastructure didn't arrive on time.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Regulatory Risk"],
        "region": "US",
        "year_founded": 2019,
        "year_shutdown": 2024,
        "funding": "$344M",
        "failure_reason": "Market adoption slower than projected"
    },

    # ===== ADDITIONAL NOTABLE FAILURES =====
    {
        "title": "Astra Space",
        "desc": "US small satellite launch startup. Raised $500M, went public via SPAC. Failed after multiple launch failures destroyed customer confidence. Rocket technology couldn't achieve reliable orbit insertion. Space is hard — demonstrated by serial launch failures.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2B", "VC-Backable", "Hardware"],
        "region": "US",
        "year_founded": 2016,
        "year_shutdown": 2024,
        "funding": "$500M",
        "failure_reason": "Launch failures, unreliable technology"
    },
    {
        "title": "Bird",
        "desc": "US electric scooter sharing pioneer. Raised $800M+, valued at $2.5B at peak. Filed for bankruptcy twice. Unit economics never worked — scooters had short lifespan (3-6 months), high vandalism/theft, seasonal demand, and municipal regulatory pushback.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Quick Cash",
        "category": "CleanTech",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "VC-Backable", "Mobile App", "Regulatory Risk"],
        "region": "US",
        "year_founded": 2017,
        "year_shutdown": 2023,
        "funding": "$800M",
        "failure_reason": "Broken unit economics, vandalism, regulation"
    },
    {
        "title": "Fisker",
        "desc": "US electric vehicle startup. Raised $1.5B, went public via SPAC at $3B valuation. Filed for bankruptcy after Ocean SUV production delays, quality problems, cash burn, and inability to raise more capital. EV startup death — capital intensity killed another one.",
        "model": "One-time",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "CleanTech",
        "persona": "The Tech Visionary",
        "tags": ["B2C", "VC-Backable", "Hardware"],
        "region": "US",
        "year_founded": 2016,
        "year_shutdown": 2024,
        "funding": "$1.5B",
        "failure_reason": "Production delays, cash burn, capital intensity"
    },
    {
        "title": "Vine (shutdown by acquisition)",
        "desc": "Short-form video app acquired by Twitter for $30M. Killed by Twitter leadership despite massive cultural impact and user base. Classic acquisition failure — parent company didn't know what to do with the asset, couldn't monetize, shut it down.",
        "model": "Freemium",
        "effort": "3-6 Months",
        "speed": "Quick Cash",
        "category": "Media",
        "persona": "The Vibe Coder",
        "tags": ["B2C", "Viral", "Mobile App", "Community"],
        "region": "US",
        "year_founded": 2012,
        "year_shutdown": 2017,
        "funding": "$30M",
        "failure_reason": "Acquisition failure, parent mismanagement"
    },
    {
        "title": "Clubhouse",
        "desc": "Audio-only social media app. Raised $200M, valued at $4B at peak. Pandemic-fueled growth evaporated as lockdowns ended. Audio-only proved to be a feature, not a platform. Couldn't retain users when competing with Twitter Spaces, Spotify Live, and Discord.",
        "model": "Freemium",
        "effort": "3-6 Months",
        "speed": "Quick Cash",
        "category": "Media",
        "persona": "The Trend Surfer",
        "tags": ["B2C", "Viral", "Mobile App", "VC-Backable"],
        "region": "US",
        "year_founded": 2020,
        "year_shutdown": 2023,
        "funding": "$200M",
        "failure_reason": "Pandemic fad, feature-not-platform"
    },
    {
        "title": "SVB (Silicon Valley Bank)",
        "desc": "US bank serving the startup ecosystem. $209B in assets. Collapsed in 2023 when concentration risk in a single industry (tech startups) created correlated failure modes. Deposit run triggered by portfolio losses in rising interest rate environment. Third largest bank failure in US history.",
        "model": "Usage-based",
        "effort": "6+ Months",
        "speed": "Long Game",
        "category": "Fintech",
        "persona": "The B2B SaaS Veteran",
        "tags": ["B2B", "Enterprise", "Regulatory Risk"],
        "region": "US",
        "year_founded": 1983,
        "year_shutdown": 2023,
        "funding": "N/A",
        "failure_reason": "Concentration risk, asset-liability mismatch"
    },
]
